# Cloud Deploy delivery pipeline configuration
# Defines the promotion pipeline: dev → staging → prod

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: order-api-pipeline
description: Order API delivery pipeline for dev, staging, and production
serialPipeline:
  stages:
    - targetId: order-api-dev
      profiles:
        - dev
    - targetId: order-api-staging
      profiles:
        - staging
    - targetId: order-api-prod
      profiles:
        - prod

---
# Cloud Run target for Development environment
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: order-api-dev
description: Development environment for Order API
run:
  location: projects/${PROJECT_ID}/locations/asia-south1

---
# Cloud Run target for Staging environment
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: order-api-staging
description: Staging environment for Order API
run:
  location: projects/${PROJECT_ID}/locations/asia-south1

---
# Cloud Run target for Production environment
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: order-api-prod
description: Production environment for Order API
requireApproval: true
run:
  location: projects/${PROJECT_ID}/locations/asia-south1
