# Skaffold configuration for Cloud Deploy
# Defines Cloud Run deployment manifests for each environment

apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: order-api
build:
  # Build configuration (handled by Cloud Build)
  local:
    push: false
manifests:
  # Cloud Run service manifests
  rawYaml:
    - k8s/cloudrun-service-dev.yaml
deploy:
  cloudrun: {}
profiles:
  # Development environment profile
  - name: dev
    manifests:
      rawYaml:
        - k8s/cloudrun-service-dev.yaml

  # Staging environment profile
  - name: staging
    manifests:
      rawYaml:
        - k8s/cloudrun-service-staging.yaml

  # Production environment profile
  - name: prod
    manifests:
      rawYaml:
        - k8s/cloudrun-service-prod.yaml

